//
//  StaticCommands.swift
//  hxguide
//
//  The static command list — every command that can be bound to a key, as
//  distinct from the typable `:` commands in Commands.swift.
//  Source: helix book/src/generated/static-cmd.md
//

import Foundation

extension Helix {

    /// A bindable Helix command: its name, what it does, and where it is bound
    /// by default. Unlike a keymap row this is keyed by *command*, so the same
    /// command appears once even when several keys reach it.
    struct StaticCommand: Identifiable, Hashable {
        /// The command name as written in `config.toml`, e.g. `move_char_left`.
        let name: String
        /// Human-readable explanation.
        let detail: String
        /// Default bindings, already formatted for display; empty when unbound.
        let bindings: String

        var id: String { name }
    }

    enum StaticCommands {
        static let all: [StaticCommand] = [
            StaticCommand(name: "no_op", detail: "Do nothing", bindings: ""),
            StaticCommand(name: "move_char_left", detail: "Move left", bindings: "normal: h, <left> — insert: <left>"),
            StaticCommand(name: "move_char_right", detail: "Move right", bindings: "normal: l, <right> — insert: <right>"),
            StaticCommand(name: "move_line_up", detail: "Move up", bindings: "normal: gk"),
            StaticCommand(name: "move_line_down", detail: "Move down", bindings: "normal: gj"),
            StaticCommand(name: "move_visual_line_up", detail: "Move up", bindings: "normal: k, <up> — insert: <up>"),
            StaticCommand(name: "move_visual_line_down", detail: "Move down", bindings: "normal: j, <down> — insert: <down>"),
            StaticCommand(name: "extend_char_left", detail: "Extend left", bindings: "select: h, <left>"),
            StaticCommand(name: "extend_char_right", detail: "Extend right", bindings: "select: l, <right>"),
            StaticCommand(name: "extend_line_up", detail: "Extend up", bindings: "select: gk"),
            StaticCommand(name: "extend_line_down", detail: "Extend down", bindings: "select: gj"),
            StaticCommand(name: "extend_visual_line_up", detail: "Extend up", bindings: "select: k, <up>"),
            StaticCommand(name: "extend_visual_line_down", detail: "Extend down", bindings: "select: j, <down>"),
            StaticCommand(name: "copy_selection_on_next_line", detail: "Copy selection on next line", bindings: "normal: C — select: C"),
            StaticCommand(name: "copy_selection_on_prev_line", detail: "Copy selection on previous line", bindings: "normal: <A-C> — select: <A-C>"),
            StaticCommand(name: "move_next_word_start", detail: "Move to start of next word", bindings: "normal: w"),
            StaticCommand(name: "move_prev_word_start", detail: "Move to start of previous word", bindings: "normal: b"),
            StaticCommand(name: "move_next_word_end", detail: "Move to end of next word", bindings: "normal: e"),
            StaticCommand(name: "move_prev_word_end", detail: "Move to end of previous word", bindings: ""),
            StaticCommand(name: "move_next_long_word_start", detail: "Move to start of next long word", bindings: "normal: W"),
            StaticCommand(name: "move_prev_long_word_start", detail: "Move to start of previous long word", bindings: "normal: B"),
            StaticCommand(name: "move_next_long_word_end", detail: "Move to end of next long word", bindings: "normal: E"),
            StaticCommand(name: "move_prev_long_word_end", detail: "Move to end of previous long word", bindings: ""),
            StaticCommand(name: "move_next_sub_word_start", detail: "Move to start of next sub word", bindings: ""),
            StaticCommand(name: "move_prev_sub_word_start", detail: "Move to start of previous sub word", bindings: ""),
            StaticCommand(name: "move_next_sub_word_end", detail: "Move to end of next sub word", bindings: ""),
            StaticCommand(name: "move_prev_sub_word_end", detail: "Move to end of previous sub word", bindings: ""),
            StaticCommand(name: "move_parent_node_end", detail: "Move to end of the parent node", bindings: "normal: <A-e>"),
            StaticCommand(name: "move_parent_node_start", detail: "Move to beginning of the parent node", bindings: "normal: <A-b>"),
            StaticCommand(name: "extend_next_word_start", detail: "Extend to start of next word", bindings: "select: w"),
            StaticCommand(name: "extend_prev_word_start", detail: "Extend to start of previous word", bindings: "select: b"),
            StaticCommand(name: "extend_next_word_end", detail: "Extend to end of next word", bindings: "select: e"),
            StaticCommand(name: "extend_prev_word_end", detail: "Extend to end of previous word", bindings: ""),
            StaticCommand(name: "extend_next_long_word_start", detail: "Extend to start of next long word", bindings: "select: W"),
            StaticCommand(name: "extend_prev_long_word_start", detail: "Extend to start of previous long word", bindings: "select: B"),
            StaticCommand(name: "extend_next_long_word_end", detail: "Extend to end of next long word", bindings: "select: E"),
            StaticCommand(name: "extend_prev_long_word_end", detail: "Extend to end of prev long word", bindings: ""),
            StaticCommand(name: "extend_next_sub_word_start", detail: "Extend to start of next sub word", bindings: ""),
            StaticCommand(name: "extend_prev_sub_word_start", detail: "Extend to start of previous sub word", bindings: ""),
            StaticCommand(name: "extend_next_sub_word_end", detail: "Extend to end of next sub word", bindings: ""),
            StaticCommand(name: "extend_prev_sub_word_end", detail: "Extend to end of prev sub word", bindings: ""),
            StaticCommand(name: "extend_parent_node_end", detail: "Extend to end of the parent node", bindings: "select: <A-e>"),
            StaticCommand(name: "extend_parent_node_start", detail: "Extend to beginning of the parent node", bindings: "select: <A-b>"),
            StaticCommand(name: "find_till_char", detail: "Move till next occurrence of char", bindings: "normal: t"),
            StaticCommand(name: "find_next_char", detail: "Move to next occurrence of char", bindings: "normal: f"),
            StaticCommand(name: "extend_till_char", detail: "Extend till next occurrence of char", bindings: "select: t"),
            StaticCommand(name: "extend_next_char", detail: "Extend to next occurrence of char", bindings: "select: f"),
            StaticCommand(name: "till_prev_char", detail: "Move till previous occurrence of char", bindings: "normal: T"),
            StaticCommand(name: "find_prev_char", detail: "Move to previous occurrence of char", bindings: "normal: F"),
            StaticCommand(name: "extend_till_prev_char", detail: "Extend till previous occurrence of char", bindings: "select: T"),
            StaticCommand(name: "extend_prev_char", detail: "Extend to previous occurrence of char", bindings: "select: F"),
            StaticCommand(name: "repeat_last_motion", detail: "Repeat last motion", bindings: "normal: <A-.> — select: <A-.>"),
            StaticCommand(name: "replace", detail: "Replace with new char", bindings: "normal: r — select: r"),
            StaticCommand(name: "switch_case", detail: "Switch (toggle) case", bindings: "normal: ~ — select: ~"),
            StaticCommand(name: "switch_to_uppercase", detail: "Switch to uppercase", bindings: "normal: <A-`> — select: <A-`>"),
            StaticCommand(name: "switch_to_lowercase", detail: "Switch to lowercase", bindings: "normal: ` — select: `"),
            StaticCommand(name: "page_up", detail: "Move page up", bindings: "normal: <C-b>, Z<C-b>, z<C-b>, <pageup>, Z<pageup>, z<pageup> — select: <C-b>, Z<C-b>, z<C-b>, <pageup>, Z<pageup>, z<pageup> — insert: <pageup>"),
            StaticCommand(name: "page_down", detail: "Move page down", bindings: "normal: <C-f>, Z<C-f>, z<C-f>, <pagedown>, Z<pagedown>, z<pagedown> — select: <C-f>, Z<C-f>, z<C-f>, <pagedown>, Z<pagedown>, z<pagedown> — insert: <pagedown>"),
            StaticCommand(name: "half_page_up", detail: "Move half page up", bindings: ""),
            StaticCommand(name: "half_page_down", detail: "Move half page down", bindings: ""),
            StaticCommand(name: "page_cursor_up", detail: "Move page and cursor up", bindings: ""),
            StaticCommand(name: "page_cursor_down", detail: "Move page and cursor down", bindings: ""),
            StaticCommand(name: "page_cursor_half_up", detail: "Move page and cursor half up", bindings: "normal: <C-u>, Z<C-u>, z<C-u>, Z<backspace>, z<backspace> — select: <C-u>, Z<C-u>, z<C-u>, Z<backspace>, z<backspace>"),
            StaticCommand(name: "page_cursor_half_down", detail: "Move page and cursor half down", bindings: "normal: <C-d>, Z<C-d>, z<C-d>, Z<space>, z<space> — select: <C-d>, Z<C-d>, z<C-d>, Z<space>, z<space>"),
            StaticCommand(name: "select_all", detail: "Select whole document", bindings: "normal: % — select: %"),
            StaticCommand(name: "select_regex", detail: "Select all regex matches inside selections", bindings: "normal: s — select: s"),
            StaticCommand(name: "split_selection", detail: "Split selections on regex matches", bindings: "normal: S — select: S"),
            StaticCommand(name: "split_selection_on_newline", detail: "Split selection on newlines", bindings: "normal: <A-s> — select: <A-s>"),
            StaticCommand(name: "merge_selections", detail: "Merge selections", bindings: "normal: <A-minus> — select: <A-minus>"),
            StaticCommand(name: "merge_consecutive_selections", detail: "Merge consecutive selections", bindings: "normal: <A-_> — select: <A-_>"),
            StaticCommand(name: "search", detail: "Search for regex pattern", bindings: "normal: /, Z/, z/ — select: /, Z/, z/"),
            StaticCommand(name: "rsearch", detail: "Reverse search for regex pattern", bindings: "normal: ?, Z?, z? — select: ?, Z?, z?"),
            StaticCommand(name: "search_next", detail: "Select next search match", bindings: "normal: n, Zn, zn — select: Zn, zn"),
            StaticCommand(name: "search_prev", detail: "Select previous search match", bindings: "normal: N, ZN, zN — select: ZN, zN"),
            StaticCommand(name: "extend_search_next", detail: "Add next search match to selection", bindings: "select: n"),
            StaticCommand(name: "extend_search_prev", detail: "Add previous search match to selection", bindings: "select: N"),
            StaticCommand(name: "search_selection", detail: "Use current selection as search pattern", bindings: "normal: <A-*> — select: <A-*>"),
            StaticCommand(name: "search_selection_detect_word_boundaries", detail: "Use current selection as the search pattern, automatically wrapping with `\\b` on word boundaries", bindings: "normal: * — select: *"),
            StaticCommand(name: "make_search_word_bounded", detail: "Modify current search to make it word bounded", bindings: ""),
            StaticCommand(name: "global_search", detail: "Global search in workspace folder", bindings: "normal: <space>/ — select: <space>/"),
            StaticCommand(name: "extend_line", detail: "Select current line, if already selected, extend to another line based on the anchor", bindings: ""),
            StaticCommand(name: "extend_line_below", detail: "Select current line, if already selected, extend to next line", bindings: "normal: x — select: x"),
            StaticCommand(name: "extend_line_above", detail: "Select current line, if already selected, extend to previous line", bindings: ""),
            StaticCommand(name: "select_line_above", detail: "Select current line, if already selected, extend or shrink line above based on the anchor", bindings: ""),
            StaticCommand(name: "select_line_below", detail: "Select current line, if already selected, extend or shrink line below based on the anchor", bindings: ""),
            StaticCommand(name: "extend_to_line_bounds", detail: "Extend selection to line bounds", bindings: "normal: X — select: X"),
            StaticCommand(name: "shrink_to_line_bounds", detail: "Shrink selection to line bounds", bindings: "normal: <A-x> — select: <A-x>"),
            StaticCommand(name: "delete_selection", detail: "Delete selection", bindings: "normal: d — select: d"),
            StaticCommand(name: "delete_selection_noyank", detail: "Delete selection without yanking", bindings: "normal: <A-d> — select: <A-d>"),
            StaticCommand(name: "change_selection", detail: "Change selection", bindings: "normal: c — select: c"),
            StaticCommand(name: "change_selection_noyank", detail: "Change selection without yanking", bindings: "normal: <A-c> — select: <A-c>"),
            StaticCommand(name: "collapse_selection", detail: "Collapse selection into single cursor", bindings: "normal: ; — select: ;"),
            StaticCommand(name: "flip_selections", detail: "Flip selection cursor and anchor", bindings: "normal: <A-;> — select: <A-;>"),
            StaticCommand(name: "ensure_selections_forward", detail: "Ensure all selections face forward", bindings: "normal: <A-:> — select: <A-:>"),
            StaticCommand(name: "insert_mode", detail: "Insert before selection", bindings: "normal: i — select: i"),
            StaticCommand(name: "append_mode", detail: "Append after selection", bindings: "normal: a — select: a"),
            StaticCommand(name: "command_mode", detail: "Enter command mode", bindings: "normal: : — select: :"),
            StaticCommand(name: "file_picker", detail: "Open file picker", bindings: "normal: <space>f — select: <space>f"),
            StaticCommand(name: "file_picker_in_current_buffer_directory", detail: "Open file picker at current buffer's directory", bindings: ""),
            StaticCommand(name: "file_picker_in_current_directory", detail: "Open file picker at current working directory", bindings: "normal: <space>F — select: <space>F"),
            StaticCommand(name: "file_explorer", detail: "Open file explorer in workspace root", bindings: "normal: <space>e — select: <space>e"),
            StaticCommand(name: "file_explorer_in_current_buffer_directory", detail: "Open file explorer at current buffer's directory", bindings: "normal: <space>E — select: <space>E"),
            StaticCommand(name: "file_explorer_in_current_directory", detail: "Open file explorer at current working directory", bindings: ""),
            StaticCommand(name: "code_action", detail: "Perform code action", bindings: "normal: <space>a — select: <space>a"),
            StaticCommand(name: "buffer_picker", detail: "Open buffer picker", bindings: "normal: <space>b — select: <space>b"),
            StaticCommand(name: "jumplist_picker", detail: "Open jumplist picker", bindings: "normal: <space>j — select: <space>j"),
            StaticCommand(name: "symbol_picker", detail: "Open symbol picker", bindings: "normal: <space>s — select: <space>s"),
            StaticCommand(name: "changed_file_picker", detail: "Open changed file picker", bindings: "normal: <space>g — select: <space>g"),
            StaticCommand(name: "select_references_to_symbol_under_cursor", detail: "Select symbol references", bindings: "normal: <space>h — select: <space>h"),
            StaticCommand(name: "workspace_symbol_picker", detail: "Open workspace symbol picker", bindings: "normal: <space>S — select: <space>S"),
            StaticCommand(name: "diagnostics_picker", detail: "Open diagnostic picker", bindings: "normal: <space>d — select: <space>d"),
            StaticCommand(name: "workspace_diagnostics_picker", detail: "Open workspace diagnostic picker", bindings: "normal: <space>D — select: <space>D"),
            StaticCommand(name: "last_picker", detail: "Open last picker", bindings: "normal: <space>' — select: <space>'"),
            StaticCommand(name: "insert_at_line_start", detail: "Insert at start of line", bindings: "normal: I — select: I"),
            StaticCommand(name: "insert_at_line_end", detail: "Insert at end of line", bindings: "normal: A — select: A"),
            StaticCommand(name: "open_below", detail: "Open new line below selection", bindings: "normal: o — select: o"),
            StaticCommand(name: "open_above", detail: "Open new line above selection", bindings: "normal: O — select: O"),
            StaticCommand(name: "normal_mode", detail: "Enter normal mode", bindings: "normal: <esc> — select: v — insert: <esc>"),
            StaticCommand(name: "select_mode", detail: "Enter selection extend mode", bindings: "normal: v"),
            StaticCommand(name: "exit_select_mode", detail: "Exit selection mode", bindings: "select: <esc>"),
            StaticCommand(name: "goto_definition", detail: "Goto definition", bindings: "normal: gd — select: gd"),
            StaticCommand(name: "goto_declaration", detail: "Goto declaration", bindings: "normal: gD — select: gD"),
            StaticCommand(name: "add_newline_above", detail: "Add newline above", bindings: "normal: [<space> — select: [<space>"),
            StaticCommand(name: "add_newline_below", detail: "Add newline below", bindings: "normal: ]<space> — select: ]<space>"),
            StaticCommand(name: "goto_type_definition", detail: "Goto type definition", bindings: "normal: gy — select: gy"),
            StaticCommand(name: "goto_implementation", detail: "Goto implementation", bindings: "normal: gi — select: gi"),
            StaticCommand(name: "goto_file_start", detail: "Goto line number <n> else file start", bindings: "normal: gg"),
            StaticCommand(name: "goto_file_end", detail: "Goto file end", bindings: ""),
            StaticCommand(name: "extend_to_file_start", detail: "Extend to line number<n> else file start", bindings: "select: gg"),
            StaticCommand(name: "extend_to_file_end", detail: "Extend to file end", bindings: ""),
            StaticCommand(name: "goto_file", detail: "Goto files/URLs in selections", bindings: "normal: gf — select: gf"),
            StaticCommand(name: "goto_file_hsplit", detail: "Goto files in selections (hsplit)", bindings: "normal: <C-w>f, <space>wf — select: <C-w>f, <space>wf"),
            StaticCommand(name: "goto_file_vsplit", detail: "Goto files in selections (vsplit)", bindings: "normal: <C-w>F, <space>wF — select: <C-w>F, <space>wF"),
            StaticCommand(name: "goto_reference", detail: "Goto references", bindings: "normal: gr — select: gr"),
            StaticCommand(name: "goto_window_top", detail: "Goto window top", bindings: "normal: gt — select: gt"),
            StaticCommand(name: "goto_window_center", detail: "Goto window center", bindings: "normal: gc — select: gc"),
            StaticCommand(name: "goto_window_bottom", detail: "Goto window bottom", bindings: "normal: gb — select: gb"),
            StaticCommand(name: "goto_last_accessed_file", detail: "Goto last accessed file", bindings: "normal: ga — select: ga"),
            StaticCommand(name: "goto_last_modified_file", detail: "Goto last modified file", bindings: "normal: gm — select: gm"),
            StaticCommand(name: "goto_last_modification", detail: "Goto last modification", bindings: "normal: g. — select: g."),
            StaticCommand(name: "goto_line", detail: "Goto line", bindings: "normal: G — select: G"),
            StaticCommand(name: "goto_last_line", detail: "Goto last line", bindings: "normal: ge"),
            StaticCommand(name: "extend_to_last_line", detail: "Extend to last line", bindings: "select: ge"),
            StaticCommand(name: "goto_first_diag", detail: "Goto first diagnostic", bindings: "normal: [D — select: [D"),
            StaticCommand(name: "goto_last_diag", detail: "Goto last diagnostic", bindings: "normal: ]D — select: ]D"),
            StaticCommand(name: "goto_next_diag", detail: "Goto next diagnostic", bindings: "normal: ]d — select: ]d"),
            StaticCommand(name: "goto_prev_diag", detail: "Goto previous diagnostic", bindings: "normal: [d — select: [d"),
            StaticCommand(name: "goto_next_change", detail: "Goto next change", bindings: "normal: ]g — select: ]g"),
            StaticCommand(name: "goto_prev_change", detail: "Goto previous change", bindings: "normal: [g — select: [g"),
            StaticCommand(name: "goto_first_change", detail: "Goto first change", bindings: "normal: [G — select: [G"),
            StaticCommand(name: "goto_last_change", detail: "Goto last change", bindings: "normal: ]G — select: ]G"),
            StaticCommand(name: "goto_line_start", detail: "Goto line start", bindings: "normal: gh, <home> — select: gh — insert: <home>"),
            StaticCommand(name: "goto_line_end", detail: "Goto line end", bindings: "normal: gl, <end> — select: gl"),
            StaticCommand(name: "goto_column", detail: "Goto column", bindings: "normal: g|"),
            StaticCommand(name: "extend_to_column", detail: "Extend to column", bindings: "select: g|"),
            StaticCommand(name: "goto_next_buffer", detail: "Goto next buffer", bindings: "normal: gn — select: gn"),
            StaticCommand(name: "goto_previous_buffer", detail: "Goto previous buffer", bindings: "normal: gp — select: gp"),
            StaticCommand(name: "goto_line_end_newline", detail: "Goto newline at line end", bindings: "insert: <end>"),
            StaticCommand(name: "goto_first_nonwhitespace", detail: "Goto first non-blank in line", bindings: "normal: gs — select: gs"),
            StaticCommand(name: "trim_selections", detail: "Trim whitespace from selections", bindings: "normal: _ — select: _"),
            StaticCommand(name: "extend_to_line_start", detail: "Extend to line start", bindings: "select: <home>"),
            StaticCommand(name: "extend_to_first_nonwhitespace", detail: "Extend to first non-blank in line", bindings: ""),
            StaticCommand(name: "extend_to_line_end", detail: "Extend to line end", bindings: "select: <end>"),
            StaticCommand(name: "extend_to_line_end_newline", detail: "Extend to line end", bindings: ""),
            StaticCommand(name: "signature_help", detail: "Show signature help", bindings: ""),
            StaticCommand(name: "smart_tab", detail: "Insert tab if all cursors have all whitespace to their left; otherwise, run a separate command.", bindings: "insert: <tab>"),
            StaticCommand(name: "insert_tab", detail: "Insert tab char", bindings: "insert: <S-tab>"),
            StaticCommand(name: "insert_newline", detail: "Insert newline char", bindings: "insert: <C-j>, <ret>"),
            StaticCommand(name: "delete_char_backward", detail: "Delete previous char", bindings: "insert: <C-h>, <backspace>, <S-backspace>"),
            StaticCommand(name: "delete_char_forward", detail: "Delete next char", bindings: "insert: <C-d>, <del>"),
            StaticCommand(name: "delete_word_backward", detail: "Delete previous word", bindings: "insert: <C-w>, <A-backspace>"),
            StaticCommand(name: "delete_word_forward", detail: "Delete next word", bindings: "insert: <A-d>, <A-del>"),
            StaticCommand(name: "kill_to_line_start", detail: "Delete till start of line", bindings: "insert: <C-u>"),
            StaticCommand(name: "kill_to_line_end", detail: "Delete till end of line", bindings: "insert: <C-k>"),
            StaticCommand(name: "undo", detail: "Undo change", bindings: "normal: u — select: u"),
            StaticCommand(name: "redo", detail: "Redo change", bindings: "normal: U — select: U"),
            StaticCommand(name: "earlier", detail: "Move backward in history", bindings: "normal: <A-u> — select: <A-u>"),
            StaticCommand(name: "later", detail: "Move forward in history", bindings: "normal: <A-U> — select: <A-U>"),
            StaticCommand(name: "commit_undo_checkpoint", detail: "Commit changes to new checkpoint", bindings: "insert: <C-s>"),
            StaticCommand(name: "yank", detail: "Yank selection", bindings: "normal: y — select: y"),
            StaticCommand(name: "yank_to_clipboard", detail: "Yank selections to clipboard", bindings: "normal: <space>y — select: <space>y"),
            StaticCommand(name: "yank_to_primary_clipboard", detail: "Yank selections to primary clipboard", bindings: ""),
            StaticCommand(name: "yank_joined", detail: "Join and yank selections", bindings: ""),
            StaticCommand(name: "yank_joined_to_clipboard", detail: "Join and yank selections to clipboard", bindings: ""),
            StaticCommand(name: "yank_main_selection_to_clipboard", detail: "Yank main selection to clipboard", bindings: "normal: <space>Y — select: <space>Y"),
            StaticCommand(name: "yank_joined_to_primary_clipboard", detail: "Join and yank selections to primary clipboard", bindings: ""),
            StaticCommand(name: "yank_main_selection_to_primary_clipboard", detail: "Yank main selection to primary clipboard", bindings: ""),
            StaticCommand(name: "replace_with_yanked", detail: "Replace with yanked text", bindings: "normal: R — select: R"),
            StaticCommand(name: "replace_selections_with_clipboard", detail: "Replace selections by clipboard content", bindings: "normal: <space>R — select: <space>R"),
            StaticCommand(name: "replace_selections_with_primary_clipboard", detail: "Replace selections by primary clipboard", bindings: ""),
            StaticCommand(name: "paste_after", detail: "Paste after selection", bindings: "normal: p — select: p"),
            StaticCommand(name: "paste_before", detail: "Paste before selection", bindings: "normal: P — select: P"),
            StaticCommand(name: "paste_clipboard_after", detail: "Paste clipboard after selections", bindings: "normal: <space>p — select: <space>p"),
            StaticCommand(name: "paste_clipboard_before", detail: "Paste clipboard before selections", bindings: "normal: <space>P — select: <space>P"),
            StaticCommand(name: "paste_primary_clipboard_after", detail: "Paste primary clipboard after selections", bindings: ""),
            StaticCommand(name: "paste_primary_clipboard_before", detail: "Paste primary clipboard before selections", bindings: ""),
            StaticCommand(name: "indent", detail: "Indent selection", bindings: "normal: <gt> — select: <gt>"),
            StaticCommand(name: "unindent", detail: "Unindent selection", bindings: "normal: <lt> — select: <lt>"),
            StaticCommand(name: "format_selections", detail: "Format selection", bindings: "normal: = — select: ="),
            StaticCommand(name: "join_selections", detail: "Join lines inside selection", bindings: "normal: J — select: J"),
            StaticCommand(name: "join_selections_space", detail: "Join lines inside selection and select spaces", bindings: "normal: <A-J> — select: <A-J>"),
            StaticCommand(name: "keep_selections", detail: "Keep selections matching regex", bindings: "normal: K — select: K"),
            StaticCommand(name: "remove_selections", detail: "Remove selections matching regex", bindings: "normal: <A-K> — select: <A-K>"),
            StaticCommand(name: "align_selections", detail: "Align selections in column", bindings: "normal: & — select: &"),
            StaticCommand(name: "keep_primary_selection", detail: "Keep primary selection", bindings: "normal: , — select: ,"),
            StaticCommand(name: "remove_primary_selection", detail: "Remove primary selection", bindings: "normal: <A-,> — select: <A-,>"),
            StaticCommand(name: "completion", detail: "Invoke completion popup", bindings: "insert: <C-x>"),
            StaticCommand(name: "hover", detail: "Show docs for item under cursor", bindings: "normal: <space>k — select: <space>k"),
            StaticCommand(name: "toggle_comments", detail: "Comment/uncomment selections", bindings: "normal: <C-c>, <space>c — select: <C-c>, <space>c"),
            StaticCommand(name: "toggle_line_comments", detail: "Line comment/uncomment selections", bindings: "normal: <space><A-c> — select: <space><A-c>"),
            StaticCommand(name: "toggle_block_comments", detail: "Block comment/uncomment selections", bindings: "normal: <space>C — select: <space>C"),
            StaticCommand(name: "rotate_selections_forward", detail: "Rotate selections forward", bindings: "normal: ) — select: )"),
            StaticCommand(name: "rotate_selections_backward", detail: "Rotate selections backward", bindings: "normal: ( — select: ("),
            StaticCommand(name: "rotate_selection_contents_forward", detail: "Rotate selection contents forward", bindings: "normal: <A-)> — select: <A-)>"),
            StaticCommand(name: "rotate_selection_contents_backward", detail: "Rotate selections contents backward", bindings: "normal: <A-(> — select: <A-(>"),
            StaticCommand(name: "reverse_selection_contents", detail: "Reverse selections contents", bindings: ""),
            StaticCommand(name: "expand_selection", detail: "Expand selection to parent syntax node", bindings: "normal: <A-o>, <A-up> — select: <A-o>, <A-up>"),
            StaticCommand(name: "shrink_selection", detail: "Shrink selection to previously expanded syntax node", bindings: "normal: <A-i>, <A-down> — select: <A-i>, <A-down>"),
            StaticCommand(name: "select_next_sibling", detail: "Select next sibling in the syntax tree", bindings: "normal: <A-n>, <A-right> — select: <A-n>, <A-right>"),
            StaticCommand(name: "select_prev_sibling", detail: "Select previous sibling the in syntax tree", bindings: "normal: <A-p>, <A-left> — select: <A-p>, <A-left>"),
            StaticCommand(name: "select_all_siblings", detail: "Select all siblings of the current node", bindings: "normal: <A-a> — select: <A-a>"),
            StaticCommand(name: "select_all_children", detail: "Select all children of the current node", bindings: "normal: <A-I>, <S-A-down> — select: <A-I>, <S-A-down>"),
            StaticCommand(name: "jump_forward", detail: "Jump forward on jumplist", bindings: "normal: <C-i>, <tab> — select: <C-i>, <tab>"),
            StaticCommand(name: "jump_backward", detail: "Jump backward on jumplist", bindings: "normal: <C-o> — select: <C-o>"),
            StaticCommand(name: "save_selection", detail: "Save current selection to jumplist", bindings: "normal: <C-s> — select: <C-s>"),
            StaticCommand(name: "jump_view_right", detail: "Jump to right split", bindings: "normal: <C-w>l, <space>wl, <C-w><C-l>, <C-w><right>, <space>w<C-l>, <space>w<right> — select: <C-w>l, <space>wl, <C-w><C-l>, <C-w><right>, <space>w<C-l>, <space>w<right>"),
            StaticCommand(name: "jump_view_left", detail: "Jump to left split", bindings: "normal: <C-w>h, <space>wh, <C-w><C-h>, <C-w><left>, <space>w<C-h>, <space>w<left> — select: <C-w>h, <space>wh, <C-w><C-h>, <C-w><left>, <space>w<C-h>, <space>w<left>"),
            StaticCommand(name: "jump_view_up", detail: "Jump to split above", bindings: "normal: <C-w>k, <C-w><up>, <space>wk, <C-w><C-k>, <space>w<up>, <space>w<C-k> — select: <C-w>k, <C-w><up>, <space>wk, <C-w><C-k>, <space>w<up>, <space>w<C-k>"),
            StaticCommand(name: "jump_view_down", detail: "Jump to split below", bindings: "normal: <C-w>j, <space>wj, <C-w><C-j>, <C-w><down>, <space>w<C-j>, <space>w<down> — select: <C-w>j, <space>wj, <C-w><C-j>, <C-w><down>, <space>w<C-j>, <space>w<down>"),
            StaticCommand(name: "swap_view_right", detail: "Swap with right split", bindings: "normal: <C-w>L, <space>wL — select: <C-w>L, <space>wL"),
            StaticCommand(name: "swap_view_left", detail: "Swap with left split", bindings: "normal: <C-w>H, <space>wH — select: <C-w>H, <space>wH"),
            StaticCommand(name: "swap_view_up", detail: "Swap with split above", bindings: "normal: <C-w>K, <space>wK — select: <C-w>K, <space>wK"),
            StaticCommand(name: "swap_view_down", detail: "Swap with split below", bindings: "normal: <C-w>J, <space>wJ — select: <C-w>J, <space>wJ"),
            StaticCommand(name: "transpose_view", detail: "Transpose splits", bindings: "normal: <C-w>t, <space>wt, <C-w><C-t>, <space>w<C-t> — select: <C-w>t, <space>wt, <C-w><C-t>, <space>w<C-t>"),
            StaticCommand(name: "rotate_view", detail: "Goto next window", bindings: "normal: <C-w>w, <space>ww, <C-w><C-w>, <space>w<C-w> — select: <C-w>w, <space>ww, <C-w><C-w>, <space>w<C-w>"),
            StaticCommand(name: "rotate_view_reverse", detail: "Goto previous window", bindings: ""),
            StaticCommand(name: "hsplit", detail: "Horizontal bottom split", bindings: "normal: <C-w>s, <space>ws, <C-w><C-s>, <space>w<C-s> — select: <C-w>s, <space>ws, <C-w><C-s>, <space>w<C-s>"),
            StaticCommand(name: "hsplit_new", detail: "Horizontal bottom split scratch buffer", bindings: "normal: <C-w>ns, <space>wns, <C-w>n<C-s>, <space>wn<C-s> — select: <C-w>ns, <space>wns, <C-w>n<C-s>, <space>wn<C-s>"),
            StaticCommand(name: "vsplit", detail: "Vertical right split", bindings: "normal: <C-w>v, <space>wv, <C-w><C-v>, <space>w<C-v> — select: <C-w>v, <space>wv, <C-w><C-v>, <space>w<C-v>"),
            StaticCommand(name: "vsplit_new", detail: "Vertical right split scratch buffer", bindings: "normal: <C-w>nv, <space>wnv, <C-w>n<C-v>, <space>wn<C-v> — select: <C-w>nv, <space>wnv, <C-w>n<C-v>, <space>wn<C-v>"),
            StaticCommand(name: "wclose", detail: "Close window", bindings: "normal: <C-w>q, <space>wq, <C-w><C-q>, <space>w<C-q> — select: <C-w>q, <space>wq, <C-w><C-q>, <space>w<C-q>"),
            StaticCommand(name: "wonly", detail: "Close windows except current", bindings: "normal: <C-w>o, <space>wo, <C-w><C-o>, <space>w<C-o> — select: <C-w>o, <space>wo, <C-w><C-o>, <space>w<C-o>"),
            StaticCommand(name: "select_register", detail: "Select register", bindings: "normal: \" — select: \""),
            StaticCommand(name: "insert_register", detail: "Insert register", bindings: "insert: <C-r>"),
            StaticCommand(name: "copy_between_registers", detail: "Copy between two registers", bindings: ""),
            StaticCommand(name: "align_view_middle", detail: "Align view middle", bindings: "normal: Zm, zm — select: Zm, zm"),
            StaticCommand(name: "align_view_top", detail: "Align view top", bindings: "normal: Zt, zt — select: Zt, zt"),
            StaticCommand(name: "align_view_center", detail: "Align view center", bindings: "normal: Zc, Zz, zc, zz — select: Zc, Zz, zc, zz"),
            StaticCommand(name: "align_view_bottom", detail: "Align view bottom", bindings: "normal: Zb, zb — select: Zb, zb"),
            StaticCommand(name: "scroll_up", detail: "Scroll view up", bindings: "normal: Zk, zk, Z<up>, z<up> — select: Zk, zk, Z<up>, z<up>"),
            StaticCommand(name: "scroll_down", detail: "Scroll view down", bindings: "normal: Zj, zj, Z<down>, z<down> — select: Zj, zj, Z<down>, z<down>"),
            StaticCommand(name: "match_brackets", detail: "Goto matching bracket", bindings: "normal: mm — select: mm"),
            StaticCommand(name: "surround_add", detail: "Surround add", bindings: "normal: ms — select: ms"),
            StaticCommand(name: "surround_replace", detail: "Surround replace", bindings: "normal: mr — select: mr"),
            StaticCommand(name: "surround_delete", detail: "Surround delete", bindings: "normal: md — select: md"),
            StaticCommand(name: "select_textobject_around", detail: "Select around object", bindings: "normal: ma — select: ma"),
            StaticCommand(name: "select_textobject_inner", detail: "Select inside object", bindings: "normal: mi — select: mi"),
            StaticCommand(name: "goto_next_function", detail: "Goto next function", bindings: "normal: ]f — select: ]f"),
            StaticCommand(name: "goto_prev_function", detail: "Goto previous function", bindings: "normal: [f — select: [f"),
            StaticCommand(name: "goto_next_class", detail: "Goto next type definition", bindings: "normal: ]t — select: ]t"),
            StaticCommand(name: "goto_prev_class", detail: "Goto previous type definition", bindings: "normal: [t — select: [t"),
            StaticCommand(name: "goto_next_parameter", detail: "Goto next parameter", bindings: "normal: ]a — select: ]a"),
            StaticCommand(name: "goto_prev_parameter", detail: "Goto previous parameter", bindings: "normal: [a — select: [a"),
            StaticCommand(name: "goto_next_comment", detail: "Goto next comment", bindings: "normal: ]c — select: ]c"),
            StaticCommand(name: "goto_prev_comment", detail: "Goto previous comment", bindings: "normal: [c — select: [c"),
            StaticCommand(name: "goto_next_test", detail: "Goto next test", bindings: "normal: ]T — select: ]T"),
            StaticCommand(name: "goto_prev_test", detail: "Goto previous test", bindings: "normal: [T — select: [T"),
            StaticCommand(name: "goto_next_entry", detail: "Goto next pairing", bindings: "normal: ]e — select: ]e"),
            StaticCommand(name: "goto_prev_entry", detail: "Goto previous pairing", bindings: "normal: [e — select: [e"),
            StaticCommand(name: "goto_next_paragraph", detail: "Goto next paragraph", bindings: "normal: ]p — select: ]p"),
            StaticCommand(name: "goto_prev_paragraph", detail: "Goto previous paragraph", bindings: "normal: [p — select: [p"),
            StaticCommand(name: "dap_launch", detail: "Launch debug target", bindings: "normal: <space>Gl — select: <space>Gl"),
            StaticCommand(name: "dap_restart", detail: "Restart debugging session", bindings: "normal: <space>Gr — select: <space>Gr"),
            StaticCommand(name: "dap_toggle_breakpoint", detail: "Toggle breakpoint", bindings: "normal: <space>Gb — select: <space>Gb"),
            StaticCommand(name: "dap_continue", detail: "Continue program execution", bindings: "normal: <space>Gc — select: <space>Gc"),
            StaticCommand(name: "dap_pause", detail: "Pause program execution", bindings: "normal: <space>Gh — select: <space>Gh"),
            StaticCommand(name: "dap_step_in", detail: "Step in", bindings: "normal: <space>Gi — select: <space>Gi"),
            StaticCommand(name: "dap_step_out", detail: "Step out", bindings: "normal: <space>Go — select: <space>Go"),
            StaticCommand(name: "dap_next", detail: "Step to next", bindings: "normal: <space>Gn — select: <space>Gn"),
            StaticCommand(name: "dap_variables", detail: "List variables", bindings: "normal: <space>Gv — select: <space>Gv"),
            StaticCommand(name: "dap_terminate", detail: "End debug session", bindings: "normal: <space>Gt — select: <space>Gt"),
            StaticCommand(name: "dap_edit_condition", detail: "Edit breakpoint condition on current line", bindings: "normal: <space>G<C-c> — select: <space>G<C-c>"),
            StaticCommand(name: "dap_edit_log", detail: "Edit breakpoint log message on current line", bindings: "normal: <space>G<C-l> — select: <space>G<C-l>"),
            StaticCommand(name: "dap_switch_thread", detail: "Switch current thread", bindings: "normal: <space>Gst — select: <space>Gst"),
            StaticCommand(name: "dap_switch_stack_frame", detail: "Switch stack frame", bindings: "normal: <space>Gsf — select: <space>Gsf"),
            StaticCommand(name: "dap_enable_exceptions", detail: "Enable exception breakpoints", bindings: "normal: <space>Ge — select: <space>Ge"),
            StaticCommand(name: "dap_disable_exceptions", detail: "Disable exception breakpoints", bindings: "normal: <space>GE — select: <space>GE"),
            StaticCommand(name: "shell_pipe", detail: "Pipe selections through shell command", bindings: "normal: | — select: |"),
            StaticCommand(name: "shell_pipe_to", detail: "Pipe selections into shell command ignoring output", bindings: "normal: <A-|> — select: <A-|>"),
            StaticCommand(name: "shell_insert_output", detail: "Insert shell command output before selections", bindings: "normal: ! — select: !"),
            StaticCommand(name: "shell_append_output", detail: "Append shell command output after selections", bindings: "normal: <A-!> — select: <A-!>"),
            StaticCommand(name: "shell_keep_pipe", detail: "Filter selections with shell predicate", bindings: "normal: $ — select: $"),
            StaticCommand(name: "suspend", detail: "Suspend and return to shell", bindings: "normal: <C-z> — select: <C-z>"),
            StaticCommand(name: "rename_symbol", detail: "Rename symbol", bindings: "normal: <space>r — select: <space>r"),
            StaticCommand(name: "increment", detail: "Increment item under cursor", bindings: "normal: <C-a> — select: <C-a>"),
            StaticCommand(name: "decrement", detail: "Decrement item under cursor", bindings: "normal: <C-x> — select: <C-x>"),
            StaticCommand(name: "record_macro", detail: "Record macro", bindings: "normal: Q — select: Q"),
            StaticCommand(name: "replay_macro", detail: "Replay macro", bindings: "normal: q — select: q"),
            StaticCommand(name: "command_palette", detail: "Open command palette", bindings: "normal: <space>? — select: <space>?"),
            StaticCommand(name: "goto_word", detail: "Jump to a two-character label", bindings: "normal: gw"),
            StaticCommand(name: "extend_to_word", detail: "Extend to a two-character label", bindings: "select: gw"),
            StaticCommand(name: "goto_next_tabstop", detail: "Goto next snippet placeholder", bindings: ""),
            StaticCommand(name: "goto_prev_tabstop", detail: "Goto next snippet placeholder", bindings: ""),
            StaticCommand(name: "rotate_selections_first", detail: "Make the first selection your primary one", bindings: ""),
            StaticCommand(name: "rotate_selections_last", detail: "Make the last selection your primary one", bindings: ""),
        ]

        /// Projection into the shared row model. The command name is the key
        /// column here — this screen is browsed by command, not by keystroke.
        static var entries: [GuideEntry] {
            all.map {
                GuideEntry(id: $0.name,
                           key: $0.name,
                           detail: $0.bindings.isEmpty
                               ? $0.detail
                               : "\($0.detail) — \($0.bindings)")
            }
        }
    }
}
